# Generated by Django 3.2.7 on 2021-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('region', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('subdept', models.CharField(max_length=50)),
                ('empid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('score', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.IntegerField(max_length=10)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
