# Generated by Django 3.2.7 on 2021-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='phoneno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='official',
            name='score',
            field=models.IntegerField(),
        ),
    ]
