# Generated by Django 3.2.7 on 2021-09-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_auto_20210928_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
