# Generated by Django 3.2.7 on 2021-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0003_alter_public_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('dept', models.CharField(choices=[('W', 'Water'), ('E', 'Electricity'), ('R', 'Roads')], max_length=1)),
                ('category', models.CharField(max_length=30)),
                ('complaint', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('US', 'unsolved'), ('S', 'solved')], max_length=2)),
            ],
        ),
    ]
