# Generated by Django 3.2.7 on 2021-09-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0004_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=180)),
                ('review', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
