# Generated by Django 3.2.7 on 2021-09-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0005_tourist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='id',
        ),
        migrations.AlterField(
            model_name='public',
            name='phoneno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
