# Generated by Django 3.2.7 on 2021-09-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0006_auto_20210929_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='sender',
            field=models.CharField(default='Nill', max_length=30),
        ),
    ]
