# Generated by Django 3.2.7 on 2021-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0007_complaints_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='landmark',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
