# Generated by Django 3.2.7 on 2021-09-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0008_alter_official_department'),
        ('trial', '0008_complaints_landmark'),
    ]

    operations = [
    ]
