# Generated by Django 3.2.7 on 2021-09-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0009_merge_20210929_1127'),
        ('trial', '0009_merge_20210929_1654'),
    ]

    operations = [
    ]
