# Generated by Django 3.2.7 on 2021-09-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0010_merge_20210929_1711'),
        ('trial', '0010_merge_20210929_1717'),
    ]

    operations = [
    ]
