# Generated by Django 3.2.7 on 2021-09-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0011_merge_20210929_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='subdept',
            field=models.CharField(choices=[('WL', 'Water Leaks'), ('SL', 'Shortage of supply'), ('PF', 'Power failure'), ('LB', 'Line damage'), ('RD', 'Road damage'), ('TR', 'Tarring required')], max_length=2),
        ),
    ]
