# Generated by Django 3.2.7 on 2021-09-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0012_alter_official_subdept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('US', 'unsolved'), ('S', 'solved')], default='US', max_length=2),
        ),
    ]
