# Generated by Django 3.2.7 on 2021-09-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0014_complaints_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='lat',
        ),
    ]
