# Generated by Django 3.2.7 on 2021-09-30 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0015_remove_complaints_lat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='postdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
