# Generated by Django 3.2.7 on 2021-09-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0016_tourist_postdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourist',
            name='postdate',
        ),
        migrations.AlterField(
            model_name='tourist',
            name='image',
            field=models.ImageField(upload_to='trial/images/'),
        ),
    ]
