# Generated by Django 3.2.7 on 2021-09-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0017_auto_20210930_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='subdept',
            field=models.CharField(choices=[('WL', 'Water Leaks'), ('SS', 'Shortage of supply'), ('PF', 'Power failure'), ('LD', 'Line damage'), ('RD', 'Road damage'), ('TR', 'Tarring required')], max_length=2),
        ),
    ]
