# Generated by Django 3.2.7 on 2021-09-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0018_alter_official_subdept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
